const unit2_1 = {
    tango: {
        入社: { 読み方: ['にゅうしゃ'], form: '名詞、する動詞、自動詞', 意味: "joining a company" },
        文房具: { 読み方: ['ぶんぼうぐ'], form: '名詞', 意味: "stationery" },
        家具: { 読み方: ['かぐ'], form: '名詞', 意味: "furniture" },
        製造販売: { 読み方: ['せいぞうはんばい'], form: '名詞', 意味: "manufacture and sales" },
        本社: { 読み方: ['ほんしゃ'], form: '名詞', 意味: "headquarters, main office" },
        席: { 読み方: ['せき'], form: '名詞', 意味: "seat, one's desk" },
        遠慮なく: { 読み方: ['えんりょなく'], form: '副詞', 意味: "without reservation" },
        それとも: { 読み方: [''], form: '接続詞', 意味: "or" },
        それと: { 読み方: [''], form: '接続詞', 意味: "also" },
        備品: { 読み方: ['びひん'], form: '名詞', 意味: "equipment, office workers use this word to refer to office supplies in general, including paper, notebooks, writing utensils, paperclips, etc." },
        必要: { 読み方: ['ひつよう'], form: 'な形容詞', 意味: "necessary, essential" },
        一般的: { 読み方: ['いっぱんてき'], form: 'な形容詞', 意味: "general" },
        日常生活: { 読み方: ['にちじょうせいかつ'], form: '名詞', 意味: "everyday life" },
        途中: { 読み方: ['とちゅう'], form: '名詞、副詞', 意味: "on the way" },
        線: { 読み方: ['せん'], form: '名詞', 意味: "line, track, route" },
        業種: { 読み方: ['ぎょうしゅ'], form: '名詞', 意味: "industry" },
        出社: { 読み方: ['しゅっしゃ'], form: '名詞、する動詞、自動詞', 意味: "commuting to work" },
        口語的: { 読み方: ['こうごてき'], form: 'な形容詞', 意味: "colloquial" },
        国際見本市: { 読み方: ['こくさいみほんいち'], form: '名詞', 意味: "international trade fair" },
        支店: { 読み方: ['してん'], form: '名詞', 意味: "branch" },
        支店長: { 読み方: ['してんちょう'], form: '名詞', 意味: "branch manager" },
        販売店: { 読み方: ['はんばいてん'], form: '名詞', 意味: "dealer" },
        得意先: { 読み方: ['とくいさき'], form: '名詞', 意味: "client, customer" },
        仕入れ先: { 読み方: ['しいれさき'], form: '名詞', 意味: "supplier" },
        御社: { 読み方: ['おんしゃ'], form: '名詞', 意味: "your company" },
        書き込み: { 読み方: ['かきこみ'], form: '名詞、する動詞', 意味: "writing" },
        くだけた表現: { 読み方: ['くだけたひょうげん'], form: '名詞', 意味: "informal expression" },
        部下: { 読み方: ['ぶか'], form: '名詞', 意味: "subordinate" },
        労う: { 読み方: ['ねぎらう'], form: '五段動詞、他動詞', 意味: "to thank for, to reward someone for their services" },
        // : { 読み方: [''], form: '', 意味: "" },
    },

    kaku: {
        にゅうしゃ: { 読み方: ['入社'], form: '名詞、する動詞、自動詞', 意味: "joining a company" },
        ぶんぼうぐ: { 読み方: ['文房具'], form: '名詞', 意味: "stationery" },
        かぐ: { 読み方: ['家具'], form: '名詞', 意味: "furniture" },
        せいぞうはんばい: { 読み方: ['製造販売'], form: '名詞', 意味: "manufacture and sales" },
        ほんしゃ: { 読み方: ['本社'], form: '名詞', 意味: "headquarters, main office" },
        せき: { 読み方: ['席'], form: '名詞', 意味: "seat, one's desk" },
        えんりょなく: { 読み方: ['遠慮なく'], form: '副詞', 意味: "without reservation" },
        びひん: { 読み方: ['備品'], form: '名詞', 意味: "equipment, office workers use this word to refer to office supplies in general, including paper, notebooks, writing utensils, paperclips, etc." },
        ひつよう: { 読み方: ['必要'], form: 'な形容詞', 意味: "necessary, essential" },
        いっぱんてき: { 読み方: ['一般的'], form: 'な形容詞', 意味: "general" },
        だんせい: { 読み方: ['男性'], form: '名詞', 意味: "male" },
        じょせい: { 読み方: ['じょせい'], form: '名詞', 意味: "female" },
        にちじょうせいかつ: { 読み方: ['日常生活'], form: '名詞', 意味: "everyday life" },
        ことば: { 読み方: ['言葉'], form: '名詞', 意味: "words, language (speech)" },
        ちかてつ: { 読み方: ['地下鉄'], form: '名詞', 意味: "subway" },
        つうきん: { 読み方: ['通勤'], form: '名詞、する動詞、自動詞', 意味: "commuting to work" },
        とちゅう: { 読み方: ['途中'], form: '名詞、副詞', 意味: "on the way" },
        せん: { 読み方: ['線'], form: '名詞', 意味: "line, track, route" },
        なれる: { 読み方: ['慣れる'], form: '一段動詞', 意味: "to get used to" },
        してん: { 読み方: ['支店'], form: '名詞', 意味: "branch" },
        めずらしい: { 読み方: ['珍しい'], form: 'い形容詞', 意味: "uncommon, rare" },
        まちがえる: { 読み方: ['間違える'], form: '一段動詞、他動詞', 意味: "to make a mistake" },
        りょうめん: { 読み方: ['両面'], form: '名詞', 意味: "both sides" },
        はいしゃ: { 読み方: ['歯医者'], form: '名詞', 意味: "dentist" },
    },

    yomerebaii: {
        stationery: { 読み方: ['文房具'], form: '名詞', 意味: "ぶんぼうぐ" },
        'commuting to work': { 読み方: ['通勤'], form: '名詞、する動詞', 意味: "つうきん" },
        'on the way': { 読み方: ['途中'], form: '名詞、副詞', 意味: "とちゅう" },
        industry: { 読み方: ['業種'], form: '名詞', 意味: "ぎょうしゅ" },
        'going to work': { 読み方: ['出社'], form: '名詞、する動詞', 意味: "しゅっしゃ" },
        colloquial: { 読み方: ['口語的'], form: '名詞', 意味: "こうごてき" },
        dealer: { 読み方: ['販売店'], form: '名詞', 意味: "はんばいてん" },
        supplier: { 読み方: ['仕入れ先'], form: '名詞', 意味: "仕入れ先" },
        'your company': { 読み方: ['御社'], form: '名詞', 意味: "名詞" },
        stapler: { 読み方: ['ホッチキス'], form: '名詞', 意味: "ホッチキス" },
        'informal expression': { 読み方: ['砕けた表現'], form: '名詞', 意味: "くだけたひょうげん" },
        subordinate: { 読み方: ['部下'], form: '名詞', 意味: "ぶか" },
        'to thank for': { 読み方: ['労う'], form: '五段動詞、他動詞', 意味: "ねぎらう" },
    },
}

export default unit2_1;