const unit4_1 = {
    tango: {
        種類: { 読み方: ['しゅるい'], form: '名詞', 意味: "document(s), paperwork" },
        急ぐ: { 読み方: ['いそぐ'], form: '五段動詞', 意味: "to hurry, to rush, to hasten" },
        仕上げる: { 読み方: ['しあげる'], form: '一段動詞、他動詞', 意味: "to finish up, to complete" },
        やっぱり: { 読み方: [''], form: '副詞', 意味: "as expected" },
        無理: { 読み方: ['むり'], form: 'な形容詞', 意味: "impossible" },
        他を当たる: { 読み方: ['ほかをあたる'], form: '表現', 意味: "to ask elsewhere" },
        役に立つ: { 読み方: ['やくにたつ'], form: '表現', 意味: "to be helpful" },
        邪魔: { 読み方: ['じゃま'], form: '名詞、する動詞、他動詞', 意味: "hindrance; disturbance" },
        斜め斜め前に: { 読み方: ['〜の　ななめまえに'], form: '', 意味: "diagonally across from~" },
        校正: { 読み方: ['こうせい'], form: '名詞', 意味: "proofreading" },
        急ぎの仕事: { 読み方: ['いそぎのしごと'], form: '名詞', 意味: "a rush job" },
        おごる: { 読み方: ['（〜に〜を）おごる'], form: '五段動詞、他動詞', 意味: "to treat someone" },
        期待: { 読み方: ['きたい'], form: '名詞、する動詞', 意味: "expectation, anticipation, hope" },
        言っとく: { 読み方: ['いっとく'], form: '表現', 意味: "for your information, I'm telling you" },
        うちの会社: { 読み方: ['うちのかいしゃ'], form: '名詞', 意味: "our company" },
        企業: { 読み方: ['きぎょう'], form: '名詞', 意味: "company, corporation, enterprise" },
        英語版: { 読み方: ['えいごばん'], form: '名詞', 意味: "english version" },
        直訳: { 読み方: ['ちょくやく'], form: '名詞', 意味: "literal translation" },
        評判: { 読み方: ['ひょうばん'], form: '名詞', 意味: "reputation" },
        直す: { 読み方: ['なおす'], form: '五段動詞、他動詞j', 意味: "to fix, to correct" },
        引き受ける: { 読み方: ['ひきうける'], form: '一段動詞、他動詞', 意味: "to accept, to undertake" },
        承知: { 読み方: ['しょうち'], form: '名詞、する動詞、他動詞', 意味: "acceptence, acknowledgement " },
        大使館: { 読み方: ['たいしかん'], form: '名詞', 意味: "embassy" },
        家具: { 読み方: ['かぐ'], form: '名詞', 意味: "furniture" },
        行う: { 読み方: ['おこなう'], form: '五段動詞、他動詞', 意味: "to perform, to conduct" },
        担当: { 読み方: ['たんとう'], form: '名詞、する動詞、他動詞', 意味: "being in charge" },
        しっかり: { 読み方: [''], form: '副詞、する動詞', 意味: "properly, well, sufficiently" },
        精一杯: { 読み方: ['せいっぱい'], form: '名詞、副詞', 意味: "one's best effort" },
        商品: { 読み方: ['しょうひん'], form: '名詞', 意味: "merchandise" },
        綴じる: { 読み方: ['とじる'], form: '一段動詞', 意味: "to close, to shut" },
        具体的: { 読み方: ['ぐたいてき'], form: 'な形容詞', 意味: "specific" },
        なんとなく: { 読み方: [''], form: '副詞', 意味: "somehow, in some vague way, for some reason or another" },
        ごちゃごちゃ: { 読み方: [''], form: 'な形容詞、副詞、する動詞', 意味: "messy, confused, disordered" },
        気がする: { 読み方: ['きがする'], form: '表現', 意味: "to feel (as if), to have a feeling (that)" },
        今のうちに: { 読み方: ['いまのうちに'], form: '表現', 意味: "while one still can, " },
        //: { 読み方: [''], form: '', 意味: "" },

        
    },

    kaku: {
        しゅるい: { 読み方: ['種類'], form: '名詞', 意味: "document(s), paperwork" },
        いそぐ: { 読み方: ['急ぐ'], form: '五段動詞', 意味: "to hurry, to rush, to hasten" },
        しあげる: { 読み方: ['仕上げる'], form: '一段動詞、他動詞', 意味: "to finish up, to complete" },
        むり: { 読み方: ['無理'], form: 'な形容詞', 意味: "impossible" },
        ほかをあたる: { 読み方: ['他を当たる'], form: '表現', 意味: "to ask elsewhere" },
        やくにたつ: { 読み方: ['役に立つ'], form: '表現', 意味: "to be helpful" },
        てんちょう: { 読み方: ['店長'], form: '名詞', 意味: "store manager" },
        きたい: { 読み方: ['期待'], form: '名詞、する動詞', 意味: "expectation, anticipation, hope" },
        きぎょう: { 読み方: ['企業'], form: '名詞', 意味: "company, corporation, enterprise" },
        えいごばん: { 読み方: ['英語版'], form: '名詞', 意味: "english version" },
        ちょくやく: { 読み方: ['直訳'], form: '名詞', 意味: "literal translation" },
        ひょうばん: { 読み方: ['評判'], form: '名詞', 意味: "reputation" },
        なおす: { 読み方: ['直す'], form: '五段動詞、他動詞j', 意味: "to fix, to correct" },
        ひきうける: { 読み方: ['引き受ける'], form: '一段動詞、他動詞', 意味: "to accept, to undertake" },
        たいしかん: { 読み方: ['たいしかん'], form: '名詞', 意味: "embassy" },
        かぐ: { 読み方: ['かぐ'], form: '名詞', 意味: "furniture" },
        おこなう: { 読み方: ['行う'], form: '五段動詞、他動詞', 意味: "to perform, to conduct" },
        たんとうしゃ: { 読み方: ['担当者'], form: '名詞、する動詞、他動詞', 意味: "person in charge" },
        しょうひん: { 読み方: ['商品'], form: '名詞', 意味: "merchandise" },
        せつめい: { 読み方: ['説明'], form: '名詞、する動詞、他動詞', 意味: "explanation" },
        へんこう: { 読み方: ['変更'], form: '名詞、する動詞、他動詞', 意味: "change; modification" },
        ばしょ: { 読み方: ['場所'], form: '名詞', 意味: "place" },
        よやくをとる: { 読み方: ['予約を取る'], form: '表現', 意味: "to make an appointment" },
    },

    yomerabaii: {
        
    },
}

export default unit4_1;