const unit3_1 = {
    tango: {
        一時: { 読み方: ['いちじ'], form: '名詞、副詞', 意味: "for a while, temporarily" },
        系列会社: { 読み方: ['けいれつがいしゃ'], form: '名詞', 意味: "affiliate company" },
        来日: { 読み方: ['らいにち'], form: '名詞、する動詞', 意味: "come to Japan" },
        恐縮: { 読み方: ['きょうしゅく'], form: '名詞、する動詞、自動詞', 意味: "to be grateful" },
        系列会社: { 読み方: ['けいれつがいしゃ'], form: '名詞', 意味: "affiliate company" },
        取締役会: { 読み方: ['とりしまりやくかい'], form: '名詞', 意味: "board meeting" },
        お礼: { 読み方: ['〜のおれいに'], form: '名詞', 意味: "thanks; grattitude; in appreciation for~" },
        ご馳走: { 読み方: ['ごちそう'], form: '名詞、する動詞、他動詞', 意味: "treat (esp. food and drink)" },
        出張: { 読み方: ['しゅっちょう'], form: '名詞、する動詞、自動詞', 意味: "business trip" },
        報告書: { 読み方: ['ほうこくしょ'], form: '名詞', 意味: "written report" },
        体調: { 読み方: ['たいちょう'], form: '名詞', 意味: "physical condition" },
        欠勤: { 読み方: ['けっきん'], form: '名詞、する動詞、自動詞', 意味: "absence (from work)" },
        出勤: { 読み方: ['しゅっきん'], form: '名詞、する動詞、自動詞', 意味: "going to work" },
        お互い様: { 読み方: ['おたがいさま'], form: 'な形容詞、名詞', 意味: "We help each other in times of trouble, you'd do the same for me, the same to you, the feeling is mutual" },
        無理をする: { 読み方: ['むりをする'], form: '表現', 意味: "to overwork oneself, to work too hard" },
        打ち合わせ: { 読み方: ['うちあわせ'], form: '名詞、する動詞、他動詞', 意味: "meeting (preliminary discussion)" },
        予約: { 読み方: ['よやく'], form: '名詞、する動詞、他動詞', 意味: "reservation" },
        商談: { 読み方: ['しょうだん'], form: '名詞、する動詞', 意味: "business negotiation" },
        その節: { 読み方: ['そのせつ'], form: '名詞、副詞', 意味: "that time" },
        豪快: { 読み方: ['ごうかい'], form: 'な形容詞', 意味: "dynamic, energetic (personality)" },
        迷惑: { 読み方: ['めいわく'], form: '名詞、な形容詞、する動詞', 意味: "trouble, bother, annoyance, nuisance, inconvenience" },
        呼びたてる: { 読み方: ['よびたてる'], form: '一段動詞、他動詞', 意味: "to call out" },
        早速: { 読み方: ['さっそく'], form: '副詞', 意味: "immediately; without delay" },
        新製品: { 読み方: ['しんせいひん'], form: '名詞', 意味: "new product" },
        
        //: { 読み方: [''], form: '', 意味: "" },
    },

    kaku: {
        きこく: { 読み方: ['帰国'], form: '名詞、する動詞、自動詞', 意味: "return to one's own country" },
        しゅっちょう: { 読み方: ['出張'], form: '名詞、する動詞、自動詞', 意味: "business trip" },
        ほうこくしょ: { 読み方: ['報告書'], form: '名詞', 意味: "written report" },
        たいちょう: { 読み方: ['体調'], form: '名詞', 意味: "physical condition" },
        けっきん: { 読み方: ['欠勤'], form: '名詞、する動詞、自動詞', 意味: "absence (from work)" },
        しゅっきん: { 読み方: ['出勤'], form: '名詞、する動詞、自動詞', 意味: "going to work" },
        おたがいさま: { 読み方: ['お互い様'], form: 'な形容詞、名詞', 意味: "We help each other in times of trouble, you'd do the same for me, the same to you, the feeling is mutual" },
        むりをする: { 読み方: ['無理をする'], form: '表現', 意味: "to overwork oneself, to work too hard" },
        うちあわせ: { 読み方: ['打ち合わせ'], form: '名詞、する動詞、他動詞', 意味: "meeting (preliminary discussion)" },
        よやく: { 読み方: ['予約'], form: '名詞、する動詞、他動詞', 意味: "reservation" },
        しょうだん: { 読み方: ['商談'], form: '名詞、する動詞', 意味: "business negotiation" },
        せつ: { 読み方: ['節'], form: '名詞', 意味: "occasion; time" },
        めいわく: { 読み方: ['迷惑'], form: '名詞、な形容詞、する動詞', 意味: "trouble, bother, annoyance, nuisance, inconvenience" },
        よびたてる: { 読み方: ['呼び立てる'], form: '一段動詞、他動詞', 意味: "to call out" },
        さっそく: { 読み方: ['早速'], form: '副詞', 意味: "immediately; without delay" },
        しんせいひん: { 読み方: ['新製品'], form: '名詞', 意味: "new product" },
        //: { 読み方: [''], form: '', 意味: "" },
    },

    yomerabaii: {
        "to overwork oneself, to work too hard": { 読み方: ['無理をする'], form: '表現', 意味: "むりをする" },
        "meeting (preliminary discussion)": { 読み方: ['打ち合わせ'], form: '名詞、する動詞、他動詞', 意味: "うちあわせ" },
        "business negotiation": { 読み方: ['商談'], form: '名詞、する動詞', 意味: "しょうだん" },
        "to cause trouble (for someone)": { 読み方: ['迷惑をかける'], form: '表現、一段動詞', 意味: "めいわくをかける" },
        "to call out": { 読み方: ['呼びたてる'], form: '一段動詞、他動詞', 意味: "よびたてる" },
    },
}

export default unit3_1;