const unit5_1 = {
    tango: {
        社員食堂: { 読み方: ['しゃいんしょくどう'], form: '名詞', 意味: "company cafeteria" },
        飲食店: { 読み方: ['いんしょくてん'], form: '名詞', 意味: "eatery, restaurant(s)" },
        外食: { 読み方: ['がいしょく'], form: '名詞、する動詞、自動詞', 意味: "eating out, dining out" },
        鶏そば: { 読み方: ['とりそば'], form: '名詞', 意味: "chicken soba" },
        給料日: { 読み方: ['きゅうりょうび'], form: '名詞', 意味: "payday" },
        高級: { 読み方: ['こうきゅう'], form: 'な形容詞', 意味: "high class, high-grade, luxury" },
        高級家具: { 読み方: ['こうきゅうかぐ'], form: '名詞', 意味: "fine furniture" },
        新作: { 読み方: ['しんさく'], form: '名詞', 意味: "a new (art) work, new collections, new creation" },
        本店: { 読み方: ['ほんてん'], form: '名詞', 意味: "head office, flagship store" },
        処理: { 読み方: ['しょり'], form: '名詞、する動詞、他動詞', 意味: "process, dealing with, handle" },
        広報部: { 読み方: ['こうほうぶ'], form: '名詞', 意味: "public relations department" },
        気に入り: { 読み方: ['きにいり'], form: '名詞、の形容詞', 意味: "favorite〜" },
        忘年会: { 読み方: ['ぼうねんかい'], form: '名詞', 意味: "year-end party" },
        幹事: { 読み方: ['かんじ'], form: '名詞', 意味: "party organizer" },
        日程: { 読み方: ['にってい'], form: '名詞', 意味: "schedule" },
        都合: { 読み方: ['つごう'], form: '副詞、名詞', 意味: "someone's availability, convenience" },
        都合を聞く: { 読み方: ['つごうをきく'], form: '表現', 意味: "to ask one's availability" },
        以降: { 読み方: ['〜いこう'], form: '名詞、副詞', 意味: "(on or) after~" },
        用意: { 読み方: ['ようい'], form: '名詞、する動詞、他動詞', 意味: "preparation, provision" },
        遠慮: { 読み方: ['えんりょ'], form: '名詞、する動詞', 意味: "reserve, constraint, restraint, modesty" },
        結構: { 読み方: ['けっこう'], form: '副詞', 意味: "pretty, quite, rather" },
        きつい: { 読み方: [''], form: 'い形容詞', 意味: "tough, tight, hard" },
        支援: { 読み方: ['しえん'], form: '名詞、する動詞、他動詞', 意味: "support, assistance" },
        費用: { 読み方: ['ひよう'], form: '名詞', 意味: "cost, expense" },
        効果: { 読み方: ['こうか'], form: '名詞', 意味: "effect" },
        職場: { 読み方: ['しょくば'], form: '名詞', 意味: "workplace" },
        準備: { 読み方: ['じゅんび'], form: '名詞、する動詞、他動詞', 意味: "preparation, arrangements" },
        比較的: { 読み方: ['ひかくてき'], form: '副詞', 意味: "comparatively, relatively" },
        //: { 読み方: [''], form: '', 意味: "" },

        
    },

    kaku: {
        しゃいんしょくどう: { 読み方: ['社員食堂'], form: '名詞', 意味: "company cafeteria" },
        いんしょくてん: { 読み方: ['飲食店'], form: '名詞', 意味: "eatery, restaurant(s)" },
        がいしょく: { 読み方: ['外食'], form: '名詞、する動詞、自動詞', 意味: "eating out, dining out" },
        きゅうりょうび: { 読み方: ['給料日'], form: '名詞', 意味: "payday" },
        こうきゅう: { 読み方: ['高級'], form: 'な形容詞', 意味: "high class, high-grade, luxury" },
        こうきゅうかぐ: { 読み方: ['高級家具'], form: '名詞', 意味: "fine furniture" },
        しんさく: { 読み方: ['新作'], form: '名詞', 意味: "a new (art) work, new collections, new creation" },
        ほんてん: { 読み方: ['本店'], form: '名詞', 意味: "head office, flagship store" },
        しょり: { 読み方: ['処理'], form: '名詞、する動詞、他動詞', 意味: "process, dealing with, handle" },
        こうほうぶ: { 読み方: ['広報部'], form: '名詞', 意味: "public relations department" },
        きにいり: { 読み方: ['気に入り'], form: '名詞、の形容詞', 意味: "favorite〜" },
        ぼうねんかい: { 読み方: ['忘年会'], form: '名詞', 意味: "year-end party" },
        かんじ: { 読み方: ['幹事'], form: '名詞', 意味: "party organizer" },
        にってい: { 読み方: ['日程'], form: '名詞', 意味: "schedule" },
        つごう: { 読み方: ['都合'], form: '副詞、名詞', 意味: "someone's availability, convenience" },
        いこう: { 読み方: ['以降'], form: '名詞、副詞', 意味: "(on or) after~" },
        ようい: { 読み方: ['用意'], form: '名詞、する動詞、他動詞', 意味: "preparation, provision" },
        えんりょ: { 読み方: ['遠慮'], form: '名詞、する動詞', 意味: "reserve, constraint, restraint, modesty" },
        けっこう: { 読み方: ['結構'], form: '副詞', 意味: "pretty, quite, rather" },
        ふえる: { 読み方: ['増える'], form: '一段動詞、自動詞', 意味: "to increase" },
        ひよう: { 読み方: ['費用'], form: '名詞', 意味: "cost, experience" },
        こうか: { 読み方: ['効果'], form: '名詞', 意味: "effect" },
        しょくば: { 読み方: ['職場'], form: '名詞', 意味: "workplace" },
        じゅんび: { 読み方: ['準備'], form: '名詞、する動詞、他動詞', 意味: "preparation, arrangements" },
        ひかくてき: { 読み方: ['比較的'], form: '副詞', 意味: "comparatively, relatively" },
    },

    yomerabaii: {
        
    },
}

export default unit5_1;