const kanji = {
    tango: {
        // Unit L_1
        株式会社: { 読み方: ['かぶしきがいしゃ'], form: '名詞', 意味: "Corporation" },
        就職: { 読み方: ['（〜に）しゅうしょく'], form: '名詞、する動詞', 意味: "to find a job (at~), finding employment" },
        社内: { 読み方: ['しゃない'], form: '名詞', 意味: "within the company" },
        配属: { 読み方: ['はいぞく'], form: '名詞、する動詞、他動詞', 意味: "assignment (of a person)" },
        配属先: { 読み方: ['はいぞくさき'], form: '名詞', 意味: "an office to which one was assigned" },
        挨拶: { 読み方: ['あいさつ'], form: '名詞、する動詞', 意味: "to greet" },
        海外事業部: { 読み方: ['かいがいじぎょうぶ'], form: '名詞', 意味: "overseas department" },
        ことになる: { 読み方: ['V〜ことになる'], form: '表現', 意味: "it is decided that" },
        一言: { 読み方: ['ひとこと'], form: '名詞、する動詞', 意味: "a brief word (to say)" },

        // Unit L_2
        入社: { 読み方: ['にゅうしゃ'], form: '名詞、する動詞、自動詞', 意味: "joining a company" },
        文房具: { 読み方: ['ぶんぼうぐ'], form: '名詞', 意味: "stationery" },
        家具: { 読み方: ['かぐ'], form: '名詞', 意味: "furniture" },
        製造販売: { 読み方: ['せいぞうはんばい'], form: '名詞', 意味: "manufacture and sales" },
        本社: { 読み方: ['ほんしゃ'], form: '名詞', 意味: "headquarters, main office" },
        席: { 読み方: ['せき'], form: '名詞', 意味: "seat, one's desk" },
        遠慮なく: { 読み方: ['えんりょなく'], form: '副詞', 意味: "without reservation" },
        それとも: { 読み方: [''], form: '接続詞', 意味: "or" },
        それと: { 読み方: [''], form: '接続詞', 意味: "also" },
        備品: { 読み方: ['びひん'], form: '名詞', 意味: "equipment, office workers use this word to refer to office supplies in general, including paper, notebooks, writing utensils, paperclips, etc." },
        必要: { 読み方: ['ひつよう'], form: 'な形容詞', 意味: "necessary, essential" },
        一般的: { 読み方: ['いっぱんてき'], form: 'な形容詞', 意味: "general" },
        日常生活: { 読み方: ['にちじょうせいかつ'], form: '名詞', 意味: "everyday life" },
        途中: { 読み方: ['とちゅう'], form: '名詞、副詞', 意味: "on the way" },
        線: { 読み方: ['せん'], form: '名詞', 意味: "line, track, route" },
        業種: { 読み方: ['ぎょうしゅ'], form: '名詞', 意味: "industry" },
        出社: { 読み方: ['しゅっしゃ'], form: '名詞、する動詞、自動詞', 意味: "commuting to work" },
        口語的: { 読み方: ['こうごてき'], form: 'な形容詞', 意味: "colloquial" },
        国際見本市: { 読み方: ['こくさいみほんいち'], form: '名詞', 意味: "international trade fair" },
        支店: { 読み方: ['してん'], form: '名詞', 意味: "branch" },
        支店長: { 読み方: ['してんちょう'], form: '名詞', 意味: "branch manager" },
        販売店: { 読み方: ['はんばいてん'], form: '名詞', 意味: "dealer" },
        得意先: { 読み方: ['とくいさき'], form: '名詞', 意味: "client, customer" },
        仕入れ先: { 読み方: ['しいれさき'], form: '名詞', 意味: "supplier" },
        御社: { 読み方: ['おんしゃ'], form: '名詞', 意味: "your company" },
        書き込み: { 読み方: ['かきこみ'], form: '名詞、する動詞', 意味: "writing" },
        くだけた表現: { 読み方: ['くだけたひょうげん'], form: '名詞', 意味: "informal expression" },
        部下: { 読み方: ['ぶか'], form: '名詞', 意味: "subordinate" },
        労う: { 読み方: ['ねぎらう'], form: '五段動詞、他動詞', 意味: "to thank for, to reward someone for their services" },
        
        // Unit L_3
        一時: { 読み方: ['いちじ'], form: '名詞、副詞', 意味: "for a while, temporarily" },
        系列会社: { 読み方: ['けいれつがいしゃ'], form: '名詞', 意味: "affiliate company" },
        来日: { 読み方: ['らいにち'], form: '名詞、する動詞', 意味: "come to Japan" },
        恐縮: { 読み方: ['きょうしゅく'], form: '名詞、する動詞、自動詞', 意味: "to be grateful" },
        系列会社: { 読み方: ['けいれつがいしゃ'], form: '名詞', 意味: "affiliate company" },
        取締役会: { 読み方: ['とりしまりやくかい'], form: '名詞', 意味: "board meeting" },
        お礼: { 読み方: ['〜のおれいに'], form: '名詞', 意味: "thanks; grattitude; in appreciation for~" },
        ご馳走: { 読み方: ['ごちそう'], form: '名詞、する動詞、他動詞', 意味: "treat (esp. food and drink)" },
        出張: { 読み方: ['しゅっちょう'], form: '名詞、する動詞、自動詞', 意味: "business trip" },
        報告書: { 読み方: ['ほうこくしょ'], form: '名詞', 意味: "written report" },
        体調: { 読み方: ['たいちょう'], form: '名詞', 意味: "physical condition" },
        欠勤: { 読み方: ['けっきん'], form: '名詞、する動詞、自動詞', 意味: "absence (from work)" },
        出勤: { 読み方: ['しゅっきん'], form: '名詞、する動詞、自動詞', 意味: "going to work" },
        お互い様: { 読み方: ['おたがいさま'], form: 'な形容詞、名詞', 意味: "We help each other in times of trouble, you'd do the same for me, the same to you, the feeling is mutual" },
        無理をする: { 読み方: ['むりをする'], form: '表現', 意味: "to overwork oneself, to work too hard" },
        打ち合わせ: { 読み方: ['うちあわせ'], form: '名詞、する動詞、他動詞', 意味: "meeting (preliminary discussion)" },
        予約: { 読み方: ['よやく'], form: '名詞、する動詞、他動詞', 意味: "reservation" },
        商談: { 読み方: ['しょうだん'], form: '名詞、する動詞', 意味: "business negotiation" },
        その節: { 読み方: ['そのせつ'], form: '名詞、副詞', 意味: "that time" },
        豪快: { 読み方: ['ごうかい'], form: 'な形容詞', 意味: "dynamic, energetic (personality)" },
        迷惑: { 読み方: ['めいわく'], form: '名詞、な形容詞、する動詞', 意味: "trouble, bother, annoyance, nuisance, inconvenience" },
        呼びたてる: { 読み方: ['よびたてる'], form: '一段動詞、他動詞', 意味: "to call out" },
        早速: { 読み方: ['さっそく'], form: '副詞', 意味: "immediately; without delay" },
        新製品: { 読み方: ['しんせいひん'], form: '名詞', 意味: "new product" },

        // Unit L_4
        種類: { 読み方: ['しゅるい'], form: '名詞', 意味: "document(s), paperwork" },
        急ぐ: { 読み方: ['いそぐ'], form: '五段動詞', 意味: "to hurry, to rush, to hasten" },
        仕上げる: { 読み方: ['しあげる'], form: '一段動詞、他動詞', 意味: "to finish up, to complete" },
        やっぱり: { 読み方: [''], form: '副詞', 意味: "as expected" },
        無理: { 読み方: ['むり'], form: 'な形容詞', 意味: "impossible" },
        他を当たる: { 読み方: ['ほかをあたる'], form: '表現', 意味: "to ask elsewhere" },
        役に立つ: { 読み方: ['やくにたつ'], form: '表現', 意味: "to be helpful" },
        邪魔: { 読み方: ['じゃま'], form: '名詞、する動詞、他動詞', 意味: "hindrance; disturbance" },
        斜め斜め前に: { 読み方: ['〜の　ななめまえに'], form: '', 意味: "diagonally across from~" },
        校正: { 読み方: ['こうせい'], form: '名詞', 意味: "proofreading" },
        急ぎの仕事: { 読み方: ['いそぎのしごと'], form: '名詞', 意味: "a rush job" },
        おごる: { 読み方: ['（〜に〜を）おごる'], form: '五段動詞、他動詞', 意味: "to treat someone" },
        期待: { 読み方: ['きたい'], form: '名詞、する動詞', 意味: "expectation, anticipation, hope" },
        言っとく: { 読み方: ['いっとく'], form: '表現', 意味: "for your information, I'm telling you" },
        うちの会社: { 読み方: ['うちのかいしゃ'], form: '名詞', 意味: "our company" },
        企業: { 読み方: ['きぎょう'], form: '名詞', 意味: "company, corporation, enterprise" },
        英語版: { 読み方: ['えいごばん'], form: '名詞', 意味: "english version" },
        直訳: { 読み方: ['ちょくやく'], form: '名詞', 意味: "literal translation" },
        評判: { 読み方: ['ひょうばん'], form: '名詞', 意味: "reputation" },
        直す: { 読み方: ['なおす'], form: '五段動詞、他動詞j', 意味: "to fix, to correct" },
        引き受ける: { 読み方: ['ひきうける'], form: '一段動詞、他動詞', 意味: "to accept, to undertake" },
        承知: { 読み方: ['しょうち'], form: '名詞、する動詞、他動詞', 意味: "acceptence, acknowledgement " },
        大使館: { 読み方: ['たいしかん'], form: '名詞', 意味: "embassy" },
        家具: { 読み方: ['かぐ'], form: '名詞', 意味: "furniture" },
        行う: { 読み方: ['おこなう'], form: '五段動詞、他動詞', 意味: "to perform, to conduct" },
        担当: { 読み方: ['たんとう'], form: '名詞、する動詞、他動詞', 意味: "being in charge" },
        しっかり: { 読み方: [''], form: '副詞、する動詞', 意味: "properly, well, sufficiently" },
        精一杯: { 読み方: ['せいっぱい'], form: '名詞、副詞', 意味: "one's best effort" },
        商品: { 読み方: ['しょうひん'], form: '名詞', 意味: "merchandise" },
        綴じる: { 読み方: ['とじる'], form: '一段動詞', 意味: "to close, to shut" },
        具体的: { 読み方: ['ぐたいてき'], form: 'な形容詞', 意味: "specific" },
        なんとなく: { 読み方: [''], form: '副詞', 意味: "somehow, in some vague way, for some reason or another" },
        ごちゃごちゃ: { 読み方: [''], form: 'な形容詞、副詞、する動詞', 意味: "messy, confused, disordered" },
        気がする: { 読み方: ['きがする'], form: '表現', 意味: "to feel (as if), to have a feeling (that)" },
        今のうちに: { 読み方: ['いまのうちに'], form: '表現', 意味: "while one still can, " },

        // Unit L_5
        社員食堂: { 読み方: ['しゃいんしょくどう'], form: '名詞', 意味: "company cafeteria" },
        飲食店: { 読み方: ['いんしょくてん'], form: '名詞', 意味: "eatery, restaurant(s)" },
        外食: { 読み方: ['がいしょく'], form: '名詞、する動詞、自動詞', 意味: "eating out, dining out" },
        鶏そば: { 読み方: ['とりそば'], form: '名詞', 意味: "chicken soba" },
        給料日: { 読み方: ['きゅうりょうび'], form: '名詞', 意味: "payday" },
        高級: { 読み方: ['こうきゅう'], form: 'な形容詞', 意味: "high class, high-grade, luxury" },
        高級家具: { 読み方: ['こうきゅうかぐ'], form: '名詞', 意味: "fine furniture" },
        新作: { 読み方: ['しんさく'], form: '名詞', 意味: "a new (art) work, new collections, new creation" },
        本店: { 読み方: ['ほんてん'], form: '名詞', 意味: "head office, flagship store" },
        処理: { 読み方: ['しょり'], form: '名詞、する動詞、他動詞', 意味: "process, dealing with, handle" },
        広報部: { 読み方: ['こうほうぶ'], form: '名詞', 意味: "public relations department" },
        気に入り: { 読み方: ['きにいり'], form: '名詞、の形容詞', 意味: "favorite〜" },
        忘年会: { 読み方: ['ぼうねんかい'], form: '名詞', 意味: "year-end party" },
        幹事: { 読み方: ['かんじ'], form: '名詞', 意味: "party organizer" },
        日程: { 読み方: ['にってい'], form: '名詞', 意味: "schedule" },
        都合: { 読み方: ['つごう'], form: '副詞、名詞', 意味: "someone's availability, convenience" },
        都合を聞く: { 読み方: ['つごうをきく'], form: '表現', 意味: "to ask one's availability" },
        以降: { 読み方: ['〜いこう'], form: '名詞、副詞', 意味: "(on or) after~" },
        用意: { 読み方: ['ようい'], form: '名詞、する動詞、他動詞', 意味: "preparation, provision" },
        遠慮: { 読み方: ['えんりょ'], form: '名詞、する動詞', 意味: "reserve, constraint, restraint, modesty" },
        結構: { 読み方: ['けっこう'], form: '副詞', 意味: "pretty, quite, rather" },
        きつい: { 読み方: [''], form: 'い形容詞', 意味: "tough, tight, hard" },
        支援: { 読み方: ['しえん'], form: '名詞、する動詞、他動詞', 意味: "support, assistance" },
        費用: { 読み方: ['ひよう'], form: '名詞', 意味: "cost, expense" },
        効果: { 読み方: ['こうか'], form: '名詞', 意味: "effect" },
        職場: { 読み方: ['しょくば'], form: '名詞', 意味: "workplace" },
        準備: { 読み方: ['じゅんび'], form: '名詞、する動詞、他動詞', 意味: "preparation, arrangements" },
        比較的: { 読み方: ['ひかくてき'], form: '副詞', 意味: "comparatively, relatively" },
        //: { 読み方: [''], form: '', 意味: "" },
    },
    kaku: {
        // Unit L_1

        // Unit L_2
        にゅうしゃ: { 読み方: ['入社'], form: '名詞、する動詞、自動詞', 意味: "joining a company" },
        ぶんぼうぐ: { 読み方: ['文房具'], form: '名詞', 意味: "stationery" },
        かぐ: { 読み方: ['家具'], form: '名詞', 意味: "furniture" },
        せいぞうはんばい: { 読み方: ['製造販売'], form: '名詞', 意味: "manufacture and sales" },
        ほんしゃ: { 読み方: ['本社'], form: '名詞', 意味: "headquarters, main office" },
        せき: { 読み方: ['席'], form: '名詞', 意味: "seat, one's desk" },
        えんりょなく: { 読み方: ['遠慮なく'], form: '副詞', 意味: "without reservation" },
        びひん: { 読み方: ['備品'], form: '名詞', 意味: "equipment, office workers use this word to refer to office supplies in general, including paper, notebooks, writing utensils, paperclips, etc." },
        ひつよう: { 読み方: ['必要'], form: 'な形容詞', 意味: "necessary, essential" },
        いっぱんてき: { 読み方: ['一般的'], form: 'な形容詞', 意味: "general" },
        だんせい: { 読み方: ['男性'], form: '名詞', 意味: "male" },
        じょせい: { 読み方: ['じょせい'], form: '名詞', 意味: "female" },
        にちじょうせいかつ: { 読み方: ['日常生活'], form: '名詞', 意味: "everyday life" },
        ことば: { 読み方: ['言葉'], form: '名詞', 意味: "words, language (speech)" },
        ちかてつ: { 読み方: ['地下鉄'], form: '名詞', 意味: "subway" },
        つうきん: { 読み方: ['通勤'], form: '名詞、する動詞、自動詞', 意味: "commuting to work" },
        とちゅう: { 読み方: ['途中'], form: '名詞、副詞', 意味: "on the way" },
        せん: { 読み方: ['線'], form: '名詞', 意味: "line, track, route" },
        なれる: { 読み方: ['慣れる'], form: '一段動詞', 意味: "to get used to" },
        してん: { 読み方: ['支店'], form: '名詞', 意味: "branch" },
        めずらしい: { 読み方: ['珍しい'], form: 'い形容詞', 意味: "uncommon, rare" },
        まちがえる: { 読み方: ['間違える'], form: '一段動詞、他動詞', 意味: "to make a mistake" },
        りょうめん: { 読み方: ['両面'], form: '名詞', 意味: "both sides" },
        はいしゃ: { 読み方: ['歯医者'], form: '名詞', 意味: "dentist" },
        
        // Unit L_3
        きこく: { 読み方: ['帰国'], form: '名詞、する動詞、自動詞', 意味: "return to one's own country" },
        しゅっちょう: { 読み方: ['出張'], form: '名詞、する動詞、自動詞', 意味: "business trip" },
        ほうこくしょ: { 読み方: ['報告書'], form: '名詞', 意味: "written report" },
        たいちょう: { 読み方: ['体調'], form: '名詞', 意味: "physical condition" },
        けっきん: { 読み方: ['欠勤'], form: '名詞、する動詞、自動詞', 意味: "absence (from work)" },
        しゅっきん: { 読み方: ['出勤'], form: '名詞、する動詞、自動詞', 意味: "going to work" },
        おたがいさま: { 読み方: ['お互い様'], form: 'な形容詞、名詞', 意味: "We help each other in times of trouble, you'd do the same for me, the same to you, the feeling is mutual" },
        むりをする: { 読み方: ['無理をする'], form: '表現', 意味: "to overwork oneself, to work too hard" },
        うちあわせ: { 読み方: ['打ち合わせ'], form: '名詞、する動詞、他動詞', 意味: "meeting (preliminary discussion)" },
        よやく: { 読み方: ['予約'], form: '名詞、する動詞、他動詞', 意味: "reservation" },
        しょうだん: { 読み方: ['商談'], form: '名詞、する動詞', 意味: "business negotiation" },
        せつ: { 読み方: ['節'], form: '名詞', 意味: "occasion; time" },
        めいわく: { 読み方: ['迷惑'], form: '名詞、な形容詞、する動詞', 意味: "trouble, bother, annoyance, nuisance, inconvenience" },
        よびたてる: { 読み方: ['呼び立てる'], form: '一段動詞、他動詞', 意味: "to call out" },
        さっそく: { 読み方: ['早速'], form: '副詞', 意味: "immediately; without delay" },
        しんせいひん: { 読み方: ['新製品'], form: '名詞', 意味: "new product" },
        
        // Unit L_4
        しゅるい: { 読み方: ['種類'], form: '名詞', 意味: "document(s), paperwork" },
        いそぐ: { 読み方: ['急ぐ'], form: '五段動詞', 意味: "to hurry, to rush, to hasten" },
        しあげる: { 読み方: ['仕上げる'], form: '一段動詞、他動詞', 意味: "to finish up, to complete" },
        むり: { 読み方: ['無理'], form: 'な形容詞', 意味: "impossible" },
        ほかをあたる: { 読み方: ['他を当たる'], form: '表現', 意味: "to ask elsewhere" },
        やくにたつ: { 読み方: ['役に立つ'], form: '表現', 意味: "to be helpful" },
        てんちょう: { 読み方: ['店長'], form: '名詞', 意味: "store manager" },
        きたい: { 読み方: ['期待'], form: '名詞、する動詞', 意味: "expectation, anticipation, hope" },
        きぎょう: { 読み方: ['企業'], form: '名詞', 意味: "company, corporation, enterprise" },
        えいごばん: { 読み方: ['英語版'], form: '名詞', 意味: "english version" },
        ちょくやく: { 読み方: ['直訳'], form: '名詞', 意味: "literal translation" },
        ひょうばん: { 読み方: ['評判'], form: '名詞', 意味: "reputation" },
        なおす: { 読み方: ['直す'], form: '五段動詞、他動詞j', 意味: "to fix, to correct" },
        ひきうける: { 読み方: ['引き受ける'], form: '一段動詞、他動詞', 意味: "to accept, to undertake" },
        たいしかん: { 読み方: ['たいしかん'], form: '名詞', 意味: "embassy" },
        かぐ: { 読み方: ['かぐ'], form: '名詞', 意味: "furniture" },
        おこなう: { 読み方: ['行う'], form: '五段動詞、他動詞', 意味: "to perform, to conduct" },
        たんとうしゃ: { 読み方: ['担当者'], form: '名詞、する動詞、他動詞', 意味: "person in charge" },
        しょうひん: { 読み方: ['商品'], form: '名詞', 意味: "merchandise" },
        せつめい: { 読み方: ['説明'], form: '名詞、する動詞、他動詞', 意味: "explanation" },
        へんこう: { 読み方: ['変更'], form: '名詞、する動詞、他動詞', 意味: "change; modification" },
        ばしょ: { 読み方: ['場所'], form: '名詞', 意味: "place" },
        よやくをとる: { 読み方: ['予約を取る'], form: '表現', 意味: "to make an appointment" },
        
        // Unit L_5
        しゃいんしょくどう: { 読み方: ['社員食堂'], form: '名詞', 意味: "company cafeteria" },
        いんしょくてん: { 読み方: ['飲食店'], form: '名詞', 意味: "eatery, restaurant(s)" },
        がいしょく: { 読み方: ['外食'], form: '名詞、する動詞、自動詞', 意味: "eating out, dining out" },
        きゅうりょうび: { 読み方: ['給料日'], form: '名詞', 意味: "payday" },
        こうきゅう: { 読み方: ['高級'], form: 'な形容詞', 意味: "high class, high-grade, luxury" },
        こうきゅうかぐ: { 読み方: ['高級家具'], form: '名詞', 意味: "fine furniture" },
        しんさく: { 読み方: ['新作'], form: '名詞', 意味: "a new (art) work, new collections, new creation" },
        ほんてん: { 読み方: ['本店'], form: '名詞', 意味: "head office, flagship store" },
        しょり: { 読み方: ['処理'], form: '名詞、する動詞、他動詞', 意味: "process, dealing with, handle" },
        こうほうぶ: { 読み方: ['広報部'], form: '名詞', 意味: "public relations department" },
        きにいり: { 読み方: ['気に入り'], form: '名詞、の形容詞', 意味: "favorite〜" },
        ぼうねんかい: { 読み方: ['忘年会'], form: '名詞', 意味: "year-end party" },
        かんじ: { 読み方: ['幹事'], form: '名詞', 意味: "party organizer" },
        にってい: { 読み方: ['日程'], form: '名詞', 意味: "schedule" },
        つごう: { 読み方: ['都合'], form: '副詞、名詞', 意味: "someone's availability, convenience" },
        いこう: { 読み方: ['以降'], form: '名詞、副詞', 意味: "(on or) after~" },
        ようい: { 読み方: ['用意'], form: '名詞、する動詞、他動詞', 意味: "preparation, provision" },
        えんりょ: { 読み方: ['遠慮'], form: '名詞、する動詞', 意味: "reserve, constraint, restraint, modesty" },
        けっこう: { 読み方: ['結構'], form: '副詞', 意味: "pretty, quite, rather" },
        ふえる: { 読み方: ['増える'], form: '一段動詞、自動詞', 意味: "to increase" },
        ひよう: { 読み方: ['費用'], form: '名詞', 意味: "cost, experience" },
        こうか: { 読み方: ['効果'], form: '名詞', 意味: "effect" },
        しょくば: { 読み方: ['職場'], form: '名詞', 意味: "workplace" },
        じゅんび: { 読み方: ['準備'], form: '名詞、する動詞、他動詞', 意味: "preparation, arrangements" },
        ひかくてき: { 読み方: ['比較的'], form: '副詞', 意味: "comparatively, relatively" },
        //: { 読み方: [''], form: '', 意味: "" },


    },

    yomerebaii: {
        // Unit L_1
        "sales department": { 読み方: ['営業部'], form: '名詞', 意味: "えいぎょうぶ" },
        "personnel department": { 読み方: ['人事部'], form: '名詞', 意味: "じんじぶ" },
        "general affair department": { 読み方: ['総務部'], form: '名詞', 意味: "そうむぶ" },
        "public relations department": { 読み方: ['広報部'], form: '名詞', 意味: "こうほうぶ" },
        "advertising department": { 読み方: ['宣伝部'], form: '名詞', 意味: "せんでんぶ" },
        "marketing department": { 読み方: ['マーケティング部'], form: '名詞', 意味: "マーケティングぶ" },
        "finance department": { 読み方: ['財務部'], form: '名詞', 意味: "ざいむぶ" },
        "chairperson": { 読み方: ['会長'], form: '名詞', 意味: "かいちょう" },
        "president": { 読み方: ['社長'], form: '名詞', 意味: "しゃちょう" },
        "vice president": { 読み方: ['副社長'], form: '名詞', 意味: "副社長" },
        "senior managing director": { 読み方: ['専務'], form: '名詞', 意味: "せんむ" },
        "managing director": { 読み方: ['常務'], form: '名詞', 意味: "じょうむ" },
        "general manager": { 読み方: ['部長'], form: '名詞', 意味: "ぶちょう" },
        "section manager": { 読み方: ['課長'], form: '名詞', 意味: "かちょう" },
        "chief": { 読み方: ['係長'], form: '名詞', 意味: "かかりちょう" },
        "supervisor": { 読み方: ['主任'], form: '名詞', 意味: "しゅにん" },

        // Unit L_2
        stationery: { 読み方: ['文房具'], form: '名詞', 意味: "ぶんぼうぐ" },
        'commuting to work': { 読み方: ['通勤'], form: '名詞、する動詞', 意味: "つうきん" },
        'on the way': { 読み方: ['途中'], form: '名詞、副詞', 意味: "とちゅう" },
        industry: { 読み方: ['業種'], form: '名詞', 意味: "ぎょうしゅ" },
        'going to work': { 読み方: ['出社'], form: '名詞、する動詞', 意味: "しゅっしゃ" },
        colloquial: { 読み方: ['口語的'], form: '名詞', 意味: "こうごてき" },
        dealer: { 読み方: ['販売店'], form: '名詞', 意味: "はんばいてん" },
        supplier: { 読み方: ['仕入れ先'], form: '名詞', 意味: "仕入れ先" },
        'your company': { 読み方: ['御社'], form: '名詞', 意味: "名詞" },
        stapler: { 読み方: ['ホッチキス'], form: '名詞', 意味: "ホッチキス" },
        'informal expression': { 読み方: ['砕けた表現'], form: '名詞', 意味: "くだけたひょうげん" },
        subordinate: { 読み方: ['部下'], form: '名詞', 意味: "ぶか" },
        'to thank for': { 読み方: ['労う'], form: '五段動詞、他動詞', 意味: "ねぎらう" },
        
        // Unit L_3
        "to overwork oneself, to work too hard": { 読み方: ['無理をする'], form: '表現', 意味: "むりをする" },
        "meeting (preliminary discussion)": { 読み方: ['打ち合わせ'], form: '名詞、する動詞、他動詞', 意味: "うちあわせ" },
        "business negotiation": { 読み方: ['商談'], form: '名詞、する動詞', 意味: "しょうだん" },
        "to cause trouble (for someone)": { 読み方: ['迷惑をかける'], form: '表現、一段動詞', 意味: "めいわくをかける" },
        "to call out": { 読み方: ['呼びたてる'], form: '一段動詞、他動詞', 意味: "よびたてる" },

        // Unit L_4
        //: { 読み方: [''], form: '', 意味: "" },
    }
}
export default kanji;   